import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Card, Modal } from 'antd'
import { useState } from 'react'
import { TestRandom } from '@/features/TestRandom'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [randomQuestions, showRandomQuestions] = useState(false);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header className={styles['Header']}>boolean function</header>
        <main className={styles['Content']}>
          <Card title="Создать тест" className={styles['ContentCard']}>
            <p>Здесь вы можете создать тест для проверки булевых функций</p>
          </Card>

          <Card title="Пройти тест" onClick={() => showRandomQuestions(true)} className={styles['ContentCard']}>
            <p>Тест выдаст рандомные вопросы</p>
          </Card>
        </main>

        {
          randomQuestions && <Modal open={randomQuestions} title="Тест на знание булевых функций" onOk={() => {
            showRandomQuestions(false);
          }} onCancel={() => {
            showRandomQuestions(false);
          }}>
            <TestRandom />
          </Modal>
        }

        <footer className={styles['Footer']}>
          @ 2023
        </footer>
      </main>
    </>
  )
}
