import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Card, Modal } from 'antd'
import { useState } from 'react'
import { TestRandom } from '@/features/TestRandom'
import { TestYourOwn } from '@/features/TestYourOwn'

const inter = Inter({ subsets: ['latin'] })

/**
 * Функция Home
 * создает визуально представление интерфейса
 * все видимые элементы на странице будут видны после ключегого слово return
 * в данной функции, мы создаем два локальных стэйта для
 * показа или случайных вопросов, или вопросов написанным юзером
 * в тэге Head мы обьявляем метаданные
 * в интерфейсе, мы увидем две карточки созданные благодря фреймоворку
 * для использования графических компонентов - antd
 */
export default function Home() {
  const [randomQuestions, showRandomQuestions] = useState(false);
  const [yourOwnQuestions, showYourOwnQuestions] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header className={styles['Header']}>boolean function</header>
        <main className={styles['Content']}>
          <Card title="Создать тест" onClick={() => showYourOwnQuestions(true)} className={styles['ContentCard']}>
            <p>Здесь вы можете создать тест для проверки булевых функций</p>
          </Card>

          <Card title="Пройти тест" onClick={() => showRandomQuestions(true)} className={styles['ContentCard']}>
            <p>Тест выдаст рандомные вопросы</p>
          </Card>
        </main>

        {
          randomQuestions && <Modal open={randomQuestions} title="Тест на знание булевых функций" onOk={() => {
            showRandomQuestions(false);
          }} onCancel={() => {
            showRandomQuestions(false);
          }}>
            <TestRandom />
          </Modal>
        }

        {
          yourOwnQuestions && <Modal open={yourOwnQuestions} title="Создание теста" onOk={() => {
            showYourOwnQuestions(false);
          }} onCancel={() => {
            showYourOwnQuestions(false);
          }}>
            <TestYourOwn />
          </Modal>
        }

        <footer className={styles['Footer']}>
          @ 2023
        </footer>
      </main>
    </>
  )
}
