import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Card } from 'antd'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header className={styles['Header']}>boolean function</header>
        <main className={styles['Content']}>
          <Card title="Создать тест" className={styles['ContentCard']}>
            <p>Здесь вы можете создать тест для проверки булевых функций</p>
          </Card>

          <Card title="Пройти тест" className={styles['ContentCard']}>
            <p>Тест выдаст рандомные вопросы</p>
          </Card>
        </main>
        <footer className={styles['Footer']}>
          @ 2023
        </footer>
      </main>
    </>
  )
}
